#!/usr/bin/env ruby
require 'obs_deploy'

host = ARGV[0]
checkdiff_params = {}

if host == "127.0.0.1"
    OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE
    checkdiff_params[target_server] = "https://#{host}:8443"
end
check_diff = ObsDeploy::CheckDiff.new(checkdiff_params)
Process.exit check_diff.has_migration? ? 1 : 0
