#!/usr/bin/env ruby
require 'obs_deploy'

host = ARGV[0]
checkdiff_params = { server: 'https://api.opensuse.org',
                     product: '15.4',
                     project: 'OBS:Server:Unstable',
                     target_server: 'https://api.opensuse.org' }


if host == "127.0.0.1"
    OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE
    checkdiff_params[target_server] = "https://#{host}:8443"
end

check_diff = ObsDeploy::CheckDiff.new(**checkdiff_params)
# 0 => new package available to deploy
# 1 => no package available to deploy
exit check_diff.new_version_available? ? 0 : 1
