#!/usr/bin/env ruby
require 'net/http'
require 'uri'
require 'json'
require 'dotenv'
require 'obs_deploy'


def commit_markdown(commit)
  "[#{commit}](https://github.com/openSUSE/open-build-service/commit/#{commit})"
end

host = ARGV[0]
checkdiff_params = {}

Dotenv.load

exit 1 if ENV['ROCKET_CHAT_URL'].nil?

# it comes from the .env file
uri = URI.parse(ENV['ROCKET_CHAT_URL'])

if host == "127.0.0.1"
    OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE
    checkdiff_params[target_server] = "https://#{host}:8443"
end

check_diff = ObsDeploy::CheckDiff.new(checkdiff_params)
obs_commit = check_diff.obs_running_commit
current_user = ENV['USER']

request = Net::HTTP::Post.new(uri)

request.content_type = "application/json"

request.body = JSON.dump({
  "message" => "Successful Deployment",
  "ruleUrl" => "https://github.com/openSUSE/open-build-service/commits/",
  "state" => "ok",
  "tags" => {
    "mention" => "Hey"
  },
  "title" => "#{current_user} just deployed commit #{commit_markdown(obs_commit)}"
})

req_options = {
  use_ssl: uri.scheme == "https",
}


response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
  http.request(request)
end

puts response.inspect
